### PR TITLE
Contains BL cond fix, buffer change, ca_verification patches, workflow change

### PR DESCRIPTION
**Pull request by borntohonk**
Contains fix to address:
https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/page-235#post-10551858

also adjusts workflow to be functional

also contains update to BL cond since the FS 19.0.0 non-tbz patch's BL is 0x94

### CODE REVIEW

**Comment by borntohonk** [comment]
@impeeza assuming you aren't automatically subscribed to PR's, this one contains more than what https://github.com/impeeza/sys-patch/pull/6 does, and doesn't rename the functions unnecessarily.

**Comment by impeeza** [comment]
Hello there,  Supposedly I am subscribed to all alerts, but... only got an alert for your message.  Thanks a lot for your great work and help.

I just look on the code and the few I can understand is very clever your modification and addition.

I am merging it now.

I only get curious about the new set of SSL mods ¿what are they for?

**Comment by impeeza** [comment]
@borntohonk I just realize this
https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/post-10553764

for me on FW 19, ATM 1.8.0 no «NoacidSigchk*» is applied. more no FS patch is applied

image

**Comment by borntohonk** [comment]
> @borntohonk I just realize this https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/post-10553764
> 
> for me on FW 19, ATM 1.8.0 no «NoacidSigchk*» is applied. more no FS patch is applied

cannot reproduce


```
[fs]
noacidsigchk1=Skipped
noacidsigchk2=Skipped
noncasigchk_old=Skipped
noncasigchk_new=Patched (sys-patch)
nocntchk=Skipped
nocntchk2=Patched (sys-patch)
[ldr]
noacidsigchk=Patched (sys-patch)
[es]
es1=Skipped
es2=Skipped
es3=Patched (sys-patch)
[nifm]
ctest=Patched (sys-patch)
[nim]
nim=Patched (sys-patch)
[ssl]
disablecaverification1=Disabled
disablecaverification2=Disabled
disablecaverification3=Disabled
[stats]
version=1.5.5-32c7757
build_date=04.12.2024 17:05:00
fw_version=19.0.1
ams_version=1.8.0
ams_target_version=0.1.0
ams_keygen=18
ams_hash=c6014b53
is_emummc=1
heap_size=4096
buffer_size=4096
patch_time=0.113s
````

**Comment by borntohonk** [comment]
from https://github.com/impeeza/sys-patch/releases/tag/v1.5.5

your repository, not mine.

**Comment by borntohonk** [comment]
syspatch

**Comment by impeeza** [comment]
> from https://github.com/impeeza/sys-patch/releases/tag/v1.5.5
> 
> your repository, not mine.

But you great, great work! I will try removing the IPS files and let you to know.

**Comment by borntohonk** [comment]
I consider this resolved/finished investigated, the gbatemp user has bad patches (either kip_patches or patches.ini) not my problem

**Comment by borntohonk** [comment]
> I only get curious about the new set of SSL mods ¿what are they for?

https://github.com/misson20000/exefs_patches?tab=readme-ov-file#disable-ca-verification

it's for specific users who need/want it, it's disabled by default, only people who need it would normally activate it.

**Pull request merged**
